# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b84cc8bde8301cc99559ef420b5d3da66764ff18e733cef0a22585fd1f570269ef89fef0aa43c90810f616b1a83df1104647a68a6a12bc166f8c5a888917983

test:
  secret_key_base: 4344ec07befe7cc7c98a5fed3d042a7617fdf791df5dbf4f1c1fcef70f91e34963b49033a4a78a3dd5c653522fb7d5028a1c3e4b7674c00619fc15c6bc53bf8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
